<script>
$(function(){
	$("#sidebar_menu_sites").addClass("active opened");
	$("#sidebar_menu_sites > a").removeClass("collapsed");
	$("#sidebar_menu_sites > ul").addClass("in");
	$("#collapse1 li.projets").addClass("active");
});
</script>
<div class="row-fluid">
        <div class="box ">
          <div class="title">
          	<div class="btn-toolbar pull-right ">
            	<div class="btn-group"> <a class="btn">Ajouter +</a> <a class="btn change_color_outside"><i class="paint_bucket"></i></a> </div>
            </div>
            <h4> <span>Liste des sites<small>(column sorting, live search, pagination)</small></span> </h4>
          </div>
          <!-- End .title -->
          
          <div class="content top">
            <table id="datatable_example" class="responsive table table-striped table-bordered" style="width:100%;margin-bottom:0; ">
              <thead>
                <tr>
                  <th class="jv no_sort"><label class="checkbox ">
                      <input type="checkbox">
                    </label></th>
                  <th class="jv no_sort">Image</th>
                  <th class="to_hide_phone  no_sort">Description</th>
                  <th class="to_hide_phone ue no_sort">Info</th>
                  <th class="">Author</th>
                  <th class="to_hide_phone span2">Views</th>
                  <th class="ue no_sort"><i class="icon-comments big"></i></th>
                  <th class="ms no_sort ">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar4.png"></td>
                  <td class="to_hide_phone">Full price for gum?!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 196 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .png</div>
                      </small></div></td>
                  <td>Fry</td>
                  <td class="to_hide_phone">46,67% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >14</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar1.png"></td>
                  <td class="to_hide_phone">Surrender your mysteries to Zoidberg!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 82 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .jpg</div>
                      </small></div></td>
                  <td>Zoidberg</td>
                  <td class="to_hide_phone">16,67% <span class="line">1,1,2,-1,-3,-2,2,4,5,2</span></td>
                  <td >21</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar2.png"></td>
                  <td class="to_hide_phone">The point is, by my standards, I won fair and square.</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 392 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .png</div>
                      </small></div></td>
                  <td>Bender</td>
                  <td class="to_hide_phone">26,67% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >12</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar3.png"></td>
                  <td class="to_hide_phone"> File not found?!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 403 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .gif</div>
                      </small></div></td>
                  <td>Fry</td>
                  <td class="to_hide_phone">7,32% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >2</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar5.png"></td>
                  <td class="to_hide_phone">I'm Santa Claus!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 546 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .jpg</div>
                      </small></div></td>
                  <td>Simpson</td>
                  <td class="to_hide_phone">48,33% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >17</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar6.png"></td>
                  <td class="to_hide_phone">And I'd do it again! And perhaps a third time!!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 294 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .png</div>
                      </small></div></td>
                  <td>Fry</td>
                  <td class="to_hide_phone">88,22% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >0</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar7.png"></td>
                  <td class="to_hide_phone">Perfectly symmetrical violence never solved anything.</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 9.996 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .psd</div>
                      </small></div></td>
                  <td>Leela</td>
                  <td class="to_hide_phone">99,67% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >93</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar4.png"></td>
                  <td class="to_hide_phone">Full price for gum?!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 196 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .png</div>
                      </small></div></td>
                  <td>Fry</td>
                  <td class="to_hide_phone">46,67% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >14</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar1.png"></td>
                  <td class="to_hide_phone">Surrender your mysteries to Zoidberg!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 82 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .jpg</div>
                      </small></div></td>
                  <td>Zoidberg</td>
                  <td class="to_hide_phone">16,67% <span class="line">1,1,2,-1,-3,-2,2,4,5,2</span></td>
                  <td >21</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar2.png"></td>
                  <td class="to_hide_phone">The point is, by my standards, I won fair and square.</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 392 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .png</div>
                      </small></div></td>
                  <td>Bender</td>
                  <td class="to_hide_phone">26,67% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >12</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar3.png"></td>
                  <td class="to_hide_phone"> File not found?!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 403 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .gif</div>
                      </small></div></td>
                  <td>Fry</td>
                  <td class="to_hide_phone">7,32% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >2</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar5.png"></td>
                  <td class="to_hide_phone">I'm Santa Claus!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 546 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .jpg</div>
                      </small></div></td>
                  <td>Simpson</td>
                  <td class="to_hide_phone">48,33% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >17</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar6.png"></td>
                  <td class="to_hide_phone">And I'd do it again! And perhaps a third time!!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 294 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .png</div>
                      </small></div></td>
                  <td>Fry</td>
                  <td class="to_hide_phone">88,22% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >0</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar7.png"></td>
                  <td class="to_hide_phone">Perfectly symmetrical violence never solved anything.</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 9.996 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .psd</div>
                      </small></div></td>
                  <td>Leela</td>
                  <td class="to_hide_phone">99,67% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >93</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar4.png"></td>
                  <td class="to_hide_phone">Full price for gum?!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 196 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .png</div>
                      </small></div></td>
                  <td>Fry</td>
                  <td class="to_hide_phone">46,67% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >14</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar1.png"></td>
                  <td class="to_hide_phone">Surrender your mysteries to Zoidberg!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 82 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .jpg</div>
                      </small></div></td>
                  <td>Zoidberg</td>
                  <td class="to_hide_phone">16,67% <span class="line">1,1,2,-1,-3,-2,2,4,5,2</span></td>
                  <td >21</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar2.png"></td>
                  <td class="to_hide_phone">The point is, by my standards, I won fair and square.</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 392 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .png</div>
                      </small></div></td>
                  <td>Bender</td>
                  <td class="to_hide_phone">26,67% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >12</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar3.png"></td>
                  <td class="to_hide_phone"> File not found?!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 403 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .gif</div>
                      </small></div></td>
                  <td>Fry</td>
                  <td class="to_hide_phone">7,32% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >2</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar5.png"></td>
                  <td class="to_hide_phone">I'm Santa Claus!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 546 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .jpg</div>
                      </small></div></td>
                  <td>Simpson</td>
                  <td class="to_hide_phone">48,33% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >17</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar6.png"></td>
                  <td class="to_hide_phone">And I'd do it again! And perhaps a third time!!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 294 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .png</div>
                      </small></div></td>
                  <td>Fry</td>
                  <td class="to_hide_phone">88,22% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >0</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar7.png"></td>
                  <td class="to_hide_phone">Perfectly symmetrical violence never solved anything.</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 9.996 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .psd</div>
                      </small></div></td>
                  <td>Leela</td>
                  <td class="to_hide_phone">99,67% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >93</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar4.png"></td>
                  <td class="to_hide_phone">Full price for gum?!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 196 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .png</div>
                      </small></div></td>
                  <td>Fry</td>
                  <td class="to_hide_phone">46,67% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >14</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar1.png"></td>
                  <td class="to_hide_phone">Surrender your mysteries to Zoidberg!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 82 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .jpg</div>
                      </small></div></td>
                  <td>Zoidberg</td>
                  <td class="to_hide_phone">16,67% <span class="line">1,1,2,-1,-3,-2,2,4,5,2</span></td>
                  <td >21</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar2.png"></td>
                  <td class="to_hide_phone">The point is, by my standards, I won fair and square.</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 392 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .png</div>
                      </small></div></td>
                  <td>Bender</td>
                  <td class="to_hide_phone">26,67% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >12</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar3.png"></td>
                  <td class="to_hide_phone"> File not found?!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 403 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .gif</div>
                      </small></div></td>
                  <td>Fry</td>
                  <td class="to_hide_phone">7,32% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >2</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar5.png"></td>
                  <td class="to_hide_phone">I'm Santa Claus!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 546 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .jpg</div>
                      </small></div></td>
                  <td>Simpson</td>
                  <td class="to_hide_phone">48,33% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >17</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar6.png"></td>
                  <td class="to_hide_phone">And I'd do it again! And perhaps a third time!!</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 294 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .png</div>
                      </small></div></td>
                  <td>Fry</td>
                  <td class="to_hide_phone">88,22% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >0</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
                <tr>
                  <td><label class="checkbox ">
                      <input type="checkbox">
                    </label></td>
                  <td><img class="thumbnail small" src="<?php echo $this->basepath("public/admin/")?>img/message_avatar7.png"></td>
                  <td class="to_hide_phone">Perfectly symmetrical violence never solved anything.</td>
                  <td class="to_hide_phone"><div class="row-fluid"><small>
                      <div class="span12"><strong>Size:</strong> 9.996 Kb</div>
                      </small></div>
                    <div class="row-fluid"><small>
                      <div class="span12"><strong>Format:</strong> .psd</div>
                      </small></div></td>
                  <td>Leela</td>
                  <td class="to_hide_phone">99,67% <span class="line">5,3,2,-1,-3,-2,2,3,5,2</span></td>
                  <td >93</td>
                  <td class="ms"><div class="btn-group"> <a class="btn btn-small"  rel="tooltip" data-placement="left" data-original-title=" Edit "><i class="gicon-edit"></i></a> <a class="btn btn-small" rel="tooltip" data-placement="top" data-original-title="View"><i class="gicon-eye-open"></i></a> <a class="btn  btn-small" rel="tooltip" data-placement="bottom" data-original-title="Remove"><i class="gicon-remove "></i></a> </div></td>
                </tr>
              </tbody>
            </table>
          </div>
          <!-- End .content --> 
        </div>
        <!-- End box --> 
      </div>
      <!-- End .row-fluid --> 
      
      <script>

      /**** Specific JS for this page ****/
      // Datatables
        $(document).ready(function() {
        
          var dontSort = [];
                    $('#datatable_example thead th').each( function () {
                        if ( $(this).hasClass( 'no_sort' )) {
                            dontSort.push( { "bSortable": false } );
                        } else {
                            dontSort.push( null );
                        }
          } );
          $('#datatable_example').dataTable( {
            "sDom": "<'row-fluid table_top_bar'<'span12'<'to_hide_phone' f>>>t<'row-fluid control-group full top' <'span4 to_hide_tablet'l><'span8 pagination'p>>",
             "aaSorting": [[ 1, "asc" ]],
            "bPaginate": true,

            "sPaginationType": "full_numbers",
            "bJQueryUI": false,
            "aoColumns": dontSort,
            
          } );
          $.extend( $.fn.dataTableExt.oStdClasses, {
            "s`": "dataTables_wrapper form-inline"
          } );

           $(".chzn-select, .dataTables_length select").chosen({
                       disable_search_threshold: 10

            });
        });
      

      </script>