<?php 

$this->headMeta()->setCharset('UTF-8');
$this->headtitle("Admin");
$this->headMeta()->appendName("viewport", "width=device-width, initial-scale=1");
$this->headLink(array(
        'rel'  => 'shortcut icon',
        'href' => 'public/admin/css/images/favicon.png',
    ), 'PREPEND')
    ->appendStylesheet($this->basepath('public/admin/js/plugins/chosen/chosen/chosen.css'))
    ->appendStylesheet($this->basepath('public/admin/css/twitter/bootstrap.css'))
    ->appendStylesheet($this->basepath('public/admin/css/base.css'))
    ->appendStylesheet($this->basepath('public/admin/css/twitter/responsive.css'))
    ->appendStylesheet($this->basepath('public/admin/css/jquery-ui-1.8.23.custom.css'));

$this->headScript()
        ->appendFile($this->basepath('public/admin/js/plugins/modernizr.custom.32549.js'))
        ->appendFile($this->basepath('public/admin/js/html5.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
        ->appendFile($this->basepath('public/admin/js/jquery.js'));

$this->inlinescript()
 //        ->appendFile($this->basepath()."/public/admin/js/plugins/enquire.min.js",'text/javascript',array('conditional' => '!IE'))
        ->appendFile($this->basepath("public/admin/js/IE7.js"),'text/javascript',array('conditional' => 'lt IE 7'))
        ->appendFile($this->basepath("public/admin/js/plugins/jquery.sparkline.min.js"))
        ->appendFile($this->basepath("public/admin/js/plugins/excanvas.compiled.js"))
        ->appendFile($this->basepath("public/admin/js/bootstrap-transition.js"))
        ->appendFile($this->basepath("public/admin/js/bootstrap-alert.js"))
        ->appendFile($this->basepath("public/admin/js/bootstrap-modal.js"))
        ->appendFile($this->basepath("public/admin/js/bootstrap-dropdown.js"))
        ->appendFile($this->basepath("public/admin/js/bootstrap-scrollspy.js"))
        ->appendFile($this->basepath("public/admin/js/bootstrap-tab.js"))
        ->appendFile($this->basepath("public/admin/js/bootstrap-tooltip.js"))
        ->appendFile($this->basepath("public/admin/js/bootstrap-popover.js"))
        ->appendFile($this->basepath("public/admin/js/bootstrap-button.js"))
        ->appendFile($this->basepath("public/admin/js/bootstrap-collapse.js"))
        ->appendFile($this->basepath("public/admin/js/bootstrap-carousel.js"))
        ->appendFile($this->basepath("public/admin/js/bootstrap-typeahead.js"))
        ->appendFile($this->basepath("public/admin/js/bootstrap-affix.js"))
        ->appendFile($this->basepath("public/admin/js/fileinput.jquery.js"))
        ->appendFile($this->basepath("public/admin/js/jquery-ui-1.8.23.custom.min.js"))
        ->appendFile($this->basepath("public/admin/js/jquery.touchdown.js"))
        ->appendFile($this->basepath("public/admin/js/plugins/jquery.uniform.min.js"))
        ->appendFile($this->basepath("public/admin/js/plugins/jquery.tinyscrollbar.min.js"))
        ->appendFile($this->basepath("public/admin/js/jnavigate.jquery.min.js"))
        ->appendFile($this->basepath("public/admin/js/jquery.touchSwipe.min.js"))
        ->appendFile($this->basepath("public/admin/js/plugins/jquery.peity.min.js"))
        ->appendFile($this->basepath("public/admin/js/plugins/chosen/chosen/chosen.jquery.min.js"))
        ->appendFile($this->basepath("public/admin/js/plugins/flot/jquery.flot.js"))
        ->appendFile($this->basepath("public/admin/js/plugins/flot/jquery.flot.resize.js"))
        ->appendFile($this->basepath("public/admin/js/plugins/datatables/js/jquery.dataTables.js"))
        ->appendFile($this->basepath("public/admin/js/plugins/knockout-2.0.0.js"))
        ->appendFile($this->basepath("public/admin/js/scripts.js"))
        ->appendFile($this->basepath("public/admin/js/todoplugin.js"))
        ->appendFile($this->basepath("public/admin/js/chartcamping.js"));

echo $this->doctype();
?>

<html class="sidebar_default  no-js" lang="en">
<head>
    <?php echo $this->headtitle();?>
	<?php echo $this->headMeta();?>
	<?php echo $this->headlink();?>
	<?php echo $this->headscript();?>
</head>

  <body>

    <div id="loading"><img src="<?php echo $this->basepath('public/admin/img/ajax-loader.gif')?>" /></div>
<div id="responsive_part">
  <div class="logo"> <a href="index.html"><span>Start</span><span class="icon"></span></a> </div>
  <ul class="nav responsive">
    <li>
      <button class="btn responsive_menu icon_item" data-toggle="collapse" data-target=".overview"> <i class="icon-reorder"></i> </button>
    </li>
  </ul>
</div>
<!-- Responsive part -->

<div id="sidebar" class="">
	<div class="scrollbar">
		<div class="track">
      		<div class="thumb">
        		<div class="end"></div>
      		</div>
    	</div>
  	</div>
  	<div class="viewport ">
    	<div class="overview collapse">
      		<div class="search row-fluid container">
        		<h2>Recherche</h2>
        		<form class="form-search">
          			<div class="input-append">
	            		<input type="text" class=" search-query" placeholder="">
	            		<button class="btn_search color_8">Recherche</button>
          			</div>
        		</form>
      		</div>
      		<ul id="sidebar_menu" class="navbar nav nav-list container full">
        		<li id="sidebar_menu_dashboard" class="accordion-group color_4">
		        	<a class="dashboard " href="">
		        		<img src="<?php echo $this->basepath('public/admin/img/menu_icons/dashboard.png')?>" />
		        		<span>Dashboard</span>
		        	</a>
		        </li>
		        <li id="sidebar_menu_sites" class="accordion-group color_7">
			        <a class="accordion-toggle widgets collapsed" data-toggle="collapse" data-parent="#sidebar_menu" href="#collapse1">
				        <img src="<?php echo $this->basepath('public/admin/img/menu_icons/forms.png')?>" />
				        <span>Projets</span>
			        </a>
			        <ul id="collapse1" class="accordion-body collapse">
			        	<li class="projets"><a href="<?= $this->url("zfcadmin/projets", array(), array(), true)?>">Tous les projets</a></li>
		            	<li class="projetenattente"><a href="<?= $this->url("zfcadmin/projetsenattente", array(), array(), true)?>">Projets en attente</a></li>
						<li class="designencours"><a href="<?= $this->url("zfcadmin/designencours", array(), array(), true)?>">Design en cours</a></li>
		            	<li class="designtermine"><a href="<?= $this->url("zfcadmin/designtermine", array(), array(), true)?>">Design terminé</a></li>
		            	<li class="developpementencours"><a href="<?= $this->url("zfcadmin/developpementencours", array(), array(), true)?>">Developpement en cours</a></li>
		            	<li class="developpementtermine"><a href="<?= $this->url("zfcadmin/developpementtermine", array(), array(), true)?>">Developpement terminé</a></li>
		            	<li class="projetentest"><a href="<?= $this->url("zfcadmin/projetsentest", array(), array(), true)?>">Projets en test</a></li>
		            	<li class="projettermine"><a href="<?= $this->url("zfcadmin/projetstermines", array(), array(), true)?>">Projets terminé</a></li>
		          	</ul>
		        </li>
		        <li id="sidebar_menu_clients" class="accordion-group color_12">
			        <a class="widgets" data-parent="#sidebar_menu" href="">
				        <img src="<?php echo $this->basepath('public/admin/img/menu_icons/users.png')?>">
				        <span>Clients</span>
			        </a>
		        </li>
		        <li id="sidebar_menu_utilisateurs" class="accordion-group color_19">
			        <a class="accordion-toggle widgets collapsed" data-toggle="collapse" data-parent="#sidebar_menu" href="#collapse2">
				        <img src="<?php echo $this->basepath('public/admin/img/menu_icons/users.png')?>" />
				        <span>Utilisateurs</span>
			        </a>
			        <ul id="collapse2" class="accordion-body collapse">
			        	<li class="utilisateurs"><a href="">Tous les utilisateurs</a></li>
		            	<li class="chefdeprojet"><a href="">Chefs de projets</a></li>
						<li class="designeur"><a href="">Designeurs</a></li>
		            	<li class="developpeur"><a href="">Développeurs</a></li>
		            	<li class="testeur"><a href="">Testeurs</a></li>
		          	</ul>
		        </li>
		        <li id="sidebar_menu_langues" class="accordion-group color_18">
			        <a class="widgets" data-parent="#sidebar_menu" href="">
				        <img src="<?php echo $this->basepath('public/admin/img/menu_icons/forms.png')?>" />
				        <span>Langues</span>
			        </a>
		        </li>
		    </ul>
      		<div class="menu_states row-fluid container ">
        		<h2 class="pull-left">Affichage</h2>
        		<div class="options pull-right">
          			<button id="menu_state_1" class="color_4" rel="tooltip" data-state ="sidebar_icons" data-placement="top" data-original-title="Icon Menu">1</button>
          			<button id="menu_state_2" class="color_4 active" rel="tooltip" data-state ="sidebar_default" data-placement="top" data-original-title="Fixed Menu">2</button>
          			<button id="menu_state_3" class="color_4" rel="tooltip" data-placement="top" data-state ="sidebar_hover" data-original-title="Floating on Hover Menu">3</button>
        		</div>
     		</div>
      		<!-- End sidebar_box --> 
      
    	</div>
	</div>
</div>
<div id="main">
	<div class="container">
    	<div class="header row-fluid">
      		<div class="logo">
	      		<a href="">
		      		<span>Start</span>
		      		<span class="icon"></span>
	      		</a>
      		</div>
      		<div class="top_right">
        		<ul class="nav nav_menu">
          			<li class="dropdown">
          				<a class="dropdown-toggle administrator" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="/page.html">
            				<div class="title">
	            				<span class="name">Yosri BAHRI</span>
	            				<span class="subtitle">WebDeveloper</span>
            				</div>
            				<span class="icon"><img src="<?php echo $this->basepath('public/admin/img/thumbnail_yosri.jpg')?>" /></span>
            			</a>
            			<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
				        	<li><a href="profile.html"><i class=" icon-user"></i> My Profile</a></li>
				            <li><a href="forms_general.html"><i class=" icon-cog"></i>Settings</a></li>
				            <li><a href="index2.html"><i class=" icon-unlock"></i>Log Out</a></li>
            			</ul>
          			</li>
        		</ul>
      		</div>
      		<!-- End top-right --> 
    	</div>
    
    	<div id="main_container">
      		<?php echo $this->layout()->content; ?>
    	</div>
    	<!-- End #container --> 
	</div>
	<div id="footer">
		<p> &copy; Start - 2013 </p>
		<span class="company_logo"><a href="http://www.pixelgrade.com"></a></span>
	</div>
</div>
	<div class="background_changer dropdown">
	  	<div class="dropdown" id="colors_pallete"> <a data-toggle="dropdown" data-target="drop4" class="change_color"></a>
	    	<ul  class="dropdown-menu pull-left" role="menu" aria-labelledby="drop4">
	      		<li><a data-color="color_0" class="color_0" tabindex="-1">1</a></li>
	      		<li><a data-color="color_1" class="color_1" tabindex="-1">1</a></li>
	      		<li><a data-color="color_2" class="color_2" tabindex="-1">2</a></li>
	      		<li><a data-color="color_3" class="color_3" tabindex="-1">3</a></li>
	      		<li><a data-color="color_4" class="color_4" tabindex="-1">4</a></li>
	      		<li><a data-color="color_5" class="color_5" tabindex="-1">5</a></li>
	      		<li><a data-color="color_6" class="color_6" tabindex="-1">6</a></li>
	      		<li><a data-color="color_7" class="color_7" tabindex="-1">7</a></li>
	      		<li><a data-color="color_8" class="color_8" tabindex="-1">8</a></li>
	      		<li><a data-color="color_9" class="color_9" tabindex="-1">9</a></li>
	      		<li><a data-color="color_10" class="color_10" tabindex="-1">10</a></li>
	      		<li><a data-color="color_11" class="color_11" tabindex="-1">10</a></li>
	      		<li><a data-color="color_12" class="color_12" tabindex="-1">12</a></li>
	      		<li><a data-color="color_13" class="color_13" tabindex="-1">13</a></li>
	      		<li><a data-color="color_14" class="color_14" tabindex="-1">14</a></li>
	      		<li><a data-color="color_15" class="color_15" tabindex="-1">15</a></li>
	      		<li><a data-color="color_16" class="color_16" tabindex="-1">16</a></li>
	      		<li><a data-color="color_17" class="color_17" tabindex="-1">17</a></li>
	      		<li><a data-color="color_18" class="color_18" tabindex="-1">18</a></li>
	      		<li><a data-color="color_19" class="color_19" tabindex="-1">19</a></li>
	      		<li><a data-color="color_20" class="color_20" tabindex="-1">20</a></li>
	      		<li><a data-color="color_21" class="color_21" tabindex="-1">21</a></li>
	      		<li><a data-color="color_22" class="color_22" tabindex="-1">22</a></li>
	      		<li><a data-color="color_23" class="color_23" tabindex="-1">23</a></li>
	      		<li><a data-color="color_24" class="color_24" tabindex="-1">24</a></li>
	      		<li><a data-color="color_25" class="color_25" tabindex="-1">25</a></li>
	    	</ul>
	  	</div>
	</div>
	<!-- End .background_changer -->
<!-- </div> -->
<!-- /container -->
	<!--[if !IE]> -->
<!--[if !IE]> -->
<script src="<?php echo $this->basepath("/public/admin/js/plugins/enquire.min.js")?>" type="text/javascript"></script> 
<!-- <![endif]-->
<!-- <![endif]-->
  <?php echo $this->inlineScript() ?>
  </body>
</html>
